ALTER TABLE agent ADD COLUMN IF NOT EXISTS model VARCHAR(100);
ALTER TABLE agent ADD COLUMN IF NOT EXISTS temperature DOUBLE PRECISION;
ALTER TABLE agent ADD COLUMN IF NOT EXISTS max_tokens INTEGER;
ALTER TABLE agent ADD COLUMN IF NOT EXISTS greeting TEXT;
